// Build-time generator: keep scripts editable, with no runtime file dependency.
#include <fstream>
#include <iostream>
#include <iterator>
#include <string>

int main(int argc, char **argv) {
    std::cout << "// Generated by build-tools/embed.cpp. Do not edit.\n";
    for (int i = 1; i < argc; ++i) {
        std::ifstream input(argv[i], std::ios::binary);
        if (!input) {
            std::cerr << "Cannot read " << argv[i] << '\n';
            return 1;
        }
        const std::string script((std::istreambuf_iterator<char>(input)), {});
        if (input.bad() || script.find(")IOC_SCRIPT\"") != std::string::npos ||
            script.find('\0') != std::string::npos) {
            std::cerr << "Cannot embed " << argv[i] << '\n';
            return 1;
        }
        std::cout << "static const char helper_" << i << "[] = R\"IOC_SCRIPT("
                  << script << ")IOC_SCRIPT\";\n";
    }
    return std::cout ? 0 : 1;
}
